locations:
  input-dir: /baimoc/wangjing/ngs/meth/data/bovine_fetus
  output-dir: results
  genome-fasta: /baimoc/wangjing/genome/bovine/Bos_taurus.ARS-UCD1.2.dna.toplevel.fa

general:
  assembly: 'bt9'
  # use one or both bisulfite aligners
  # bwameth is faster and uses less resources
  use_bwameth: False
  # bismark is gold standard and uses sensible defaults
  use_bismark: True
  trimming: False
  methylation-calling:
    minimum-coverage: 10
    minimum-quality: 10
    # this applies to bwameth only
    keep-singleton: False
    # keep-duplicates can be Auto/True/False, Auto decides based on protocol
    keep-duplicates: Auto
  export-bigwig:
    # extract/export contexts other than CpG?
    context:
      cpg:
        export: True
        # join both strands and summarize coverage/methylation?
        destrand: True
      chg:
        export: False
        destrand: False
      chh:
        export: False
        destrand: False
  reports:
    TSS_plotlength: 5000
  differential-methylation:
    cores: 1
    qvalue: 0.01
    difference: 25
    annotation:
      cpgIsland-bedfile: ''
      refGenes-bedfile: ''
      # download cpgIsland-bedfile or refGenes-bedfile automatically if not given?
      webfetch: no

DManalyses:
  # The names of analyses can be anything but they have to be unique
  # for each combination of case control group comparisons.

  qiannaovshounao:
    # If multiple sample names are provided, they must be separated by comma.
    treatment_sample_groups: "qiannao"
    control_sample_groups: "hounao"
    # If multiple contexts are provided, they must be separated by comma.
    # context: "Cpg,CHG,CHH"
    context: "CpG,CHG,CHH"

  # multipleTreat:
  #   treatment_sample_groups: "MED2,MED1"
  #   control_sample_groups: "H2O"

  # withinGroup:
  #   treatment_sample_groups: "MED2,MED1,H2O"
  #   control_sample_groups: "MED2,MED1,H2O"


execution:
  jobs: 32
  nice: 19
  memory: 131072 # 128G
  rules:
    __default__:
      threads: 1
      memory: 10240
    fastqc:
      threads: 6
      memory: 16384
    multiqc:
      threads: 6
      memory: 16384
    trim_galore:
      threads: 12
      memory: 16384
    bwameth:
      threads: 12
      memory: 65536
    bismark:
      threads: 16
      memory: 65536
    diffmeth:
      threads: 8
      memory: 32768
    methCall:
      threads: 8
      memory: 65536
    methSeg:
      threads: 8
      memory: 65536
    methUnite:
      threads: 8
      memory: 65536
    final_report:
      threads: 1
      memory: 65536
    sort_index_bam_bwameth:
      threads: 6
      memory: 65536
    samtools_sort_bam:
      threads: 6
      memory: 65536
    samtools_stats:
      threads: 6
      memory: 65536
    samblaster_markdup_sort:
      threads: 12
      memory: 65536 # memory per thread
    bwameth_align_trimmed:
      threads: 12
      memory: 65536
    methyldackel_extract:
      threads: 6
      memory: 65536
    export_tabix_bigwig:
      threads: 8
      memory: 65536

tools:
  fastqc:
    executable: "fastqc"
    args: ""
  multiqc:
    executable: "multiqc"
    args: ""
  trim_galore:
    executable: "trim_galore"
    args: ""
  cutadapt:
    executable: "cutadapt"
    args: ""
  bwameth:
    executable: "bwameth.py"
    args: ""
  bowtie2:
    executable: "bowtie2"
    args: ""
  bismark:
    executable: "bismark"
    args: " -N 0 -L 20 "
  deduplicate-bismark:
    executable: "deduplicate-bismark"
    args: ""
  bismark_genome_preparation:
    executable: "bismark_genome_preparation"
    args: ""
  samtools:
    executable: "samtools"
    args: ""
  samblaster:
    executable: "samblaster"
    args: ""
  methyldackel:
    executable: "MethylDackel"
    args: ""
  bowtie2-inspect:
    executable: "bowtie2-inspect"
    args: ""
  Rscript:
    executable: "Rscript"
    args: "--vanilla"
  cut:
    executable: "cut"
    args: ""
  sed:
    executable: "sed"
    args: ""
  grep:
    executable: "grep"
    args: ""
