locations:
  input-dir: sra
  output-dir: results
  genome-fasta: resources/sample.fasta

general:
  assembly: 'hg19'
  # use one or both bisulfite aligners
  # bwameth is faster and uses less resources
  use_bwameth: True
  # bismark is gold standard and uses sensible defaults
  use_bismark: True
  methylation-calling:
    minimum-coverage: 10
    minimum-quality: 10
    # this applies to bwameth only
    keep-singleton: False
    # keep-duplicates can be Auto/True/False, Auto decides based on protocol
    keep-duplicates: Auto
  export-bigwig:
    # extract/export contexts other than CpG?
    context:
      cpg:
        export: True
        # join both strands and summarize coverage/methylation?
        destrand: True
      chg:
        export: False
        destrand: False
      chh:
        export: False
        destrand: False
  reports:
    TSS_plotlength: 5000
  differential-methylation:
    cores: 1
    qvalue: 0.01
    difference: 25
    annotation:
      cpgIsland-bedfile: ''
      refGenes-bedfile: ''
      # download cpgIsland-bedfile or refGenes-bedfile automatically if not given?
      webfetch: no

DManalyses:
  # The names of analyses can be anything but they have to be unique
  # for each combination of case control group comparisons.

  med1vsh2o:
    # If multiple sample names are provided, they must be separated by comma.
    treatment_sample_groups: "MED1"
    control_sample_groups: "H2O"
    # If multiple contexts are provided, they must be separated by comma.
    # context: "Cpg,CHG,CHH"
    context: "CpG"

  # multipleTreat:
  #   treatment_sample_groups: "MED2,MED1"
  #   control_sample_groups: "H2O"

  # withinGroup:
  #   treatment_sample_groups: "MED2,MED1,H2O"
  #   control_sample_groups: "MED2,MED1,H2O"


execution:
  jobs: 6
  nice: 19
  rules:
    __default__:
      threads: 1
      memory: 10G
    fastqc:
      threads: 6
      memory: 16G
    trim_galore:
      threads: 6
      memory: 16G
    bismark_align_and_map:
      threads: 6
      memory: 19G
    diffmeth:
      threads: 1
      memory: 30G
    final_report:
      threads: 1
      memory: 40G
    sort_index_bam_bwameth:
      threads: 12
      memory: 12G
    samtools_sort_bam:
      threads: 12
      memory: 12G
    samblaster_markdup_sort:
      threads: 12
      memory: 2G # memory per thread
    bwameth_align_trimmed:
      threads: 12
      memory: 20G
    methyldackel_extract:
      threads: 4
      memory: 6G
    export_tabix_bigwig:
      threads: 8
      memory: 8G

tools:
  fastqc:
    executable: "fastqc"
    args: ""
  multiqc:
    executable: "multiqc"
    args: ""
  trim_galore:
    executable: "trim_galore"
    args: ""
  cutadapt:
    executable: "cutadapt"
    args: ""
  bwameth:
    executable: "bwameth.py"
    args: ""
  bowtie2:
    executable: "bowtie2"
    args: ""
  bismark:
    executable: "bismark"
    args: " -N 0 -L 20 "
    cores: 3
  deduplicate-bismark:
    executable: "deduplicate-bismark"
    args: ""
  bismark_genome_preparation:
    executable: "bismark_genome_preparation"
    args: ""
  samtools:
    executable: "samtools"
    args: ""
  samblaster:
    executable: "samblaster"
    args: ""
  methyldackel:
    executable: "MethylDackel"
    args: ""
  bowtie2-inspect:
    executable: "bowtie2-inspect"
    args: ""
  Rscript:
    executable: "Rscript"
    args: "--vanilla"
  cut:
    executable: "cut"
    args: ""
  sed:
    executable: "sed"
    args: ""
  grep:
    executable: "grep"
    args: ""
